# Use the official Node.js base image with version 18
FROM node:18

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY package.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code to the container
COPY . .

# Expose the port that the app will run on
# EXPOSE 3000

# Start the Node.js app
CMD ["npm", "start"]
